In [2]:
print ("hello world")
shopping_list = ["bananas","carrots","tea"]
print(shopping_list)

hello world
['bananas', 'carrots', 'tea']


In [3]:
import csv as csv 
import numpy as np

csv_file_object = csv.reader(open('c:/train.csv', 'rt')) 
next(csv_file_object)
data=[]
for row in csv_file_object:
    data.append(row)
data = np.array(data) 

print (data[0,4])

male


In [4]:
print (data[0,4])

male


In [5]:
print (data[0::,4])

['male' 'female' 'female' 'female' 'male' 'male' 'male' 'male' 'female'
 'female' 'female' 'female' 'male' 'male' 'female' 'female' 'male' 'male'
 'female' 'female' 'male' 'male' 'female' 'male' 'female' 'female' 'male'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'male' 'male'
 'male' 'male' 'female' 'female' 'female' 'female' 'male' 'female' 'female'
 'male' 'male' 'female' 'male' 'female' 'male' 'male' 'female' 'female'
 'male' 'male' 'female' 'male' 'female' 'male' 'male' 'female' 'male'
 'male' 'male' 'male' 'female' 'male' 'female' 'male' 'male' 'female'
 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'female' 'male' 'male'
 'female' 'male' 'female' 'female' 'male' 'male' 'female' 'male' 'male'
 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'female' 'male' 'female'
 'male' 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'female' 'male'
 'female' 'male' 'female' 'female' 'male' 'male' 'male' 'male' 'female'
 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'ma

In [6]:
number_passengers = np.size(data[0::,1].astype(np.float))

In [7]:
number_survived = np.sum(data[0::,1].astype(np.float))

In [8]:
proportion_survivors = number_survived / number_passengers

In [9]:
print (proportion_survivors)

0.383838383838


In [10]:
print (number_survived)

342.0


In [11]:
women_only_stats = data[0::,4] == "female"

In [12]:
men_only_stats = data[0::,4] != "female" 

In [13]:
women_onboard = data[women_only_stats,1].astype(np.float)     
men_onboard = data[men_only_stats,1].astype(np.float)

In [14]:
proportion_women_survived = \
                       np.sum(women_onboard) / np.size(women_onboard)  
proportion_men_survived = \
                       np.sum(men_onboard) / np.size(men_onboard) 

In [15]:
print ('Proportion of women who survived is %s' % proportion_women_survived)
print ('Proportion of men who survived is %s' % proportion_men_survived)

Proportion of women who survived is 0.742038216561
Proportion of men who survived is 0.188908145581


In [16]:
test_file = open('C:/test/train.csv', 'rt')
test_file_object = csv.reader(test_file)
next(test_file)

'PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked\n'

In [17]:
prediction_file = open("C:/test/output.csv", "w")
prediction_file_object = csv.writer(prediction_file)
prediction_file_object.writerow(["PassengerId", "Survived"])
for row in test_file_object:       
    if row[3] == 'female':                                       
        prediction_file_object.writerow([row[0],'1'])   
    else:                              
        prediction_file_object.writerow([row[0],'0'])    
test_file.close()
prediction_file.close()

In [18]:
fare_ceiling = 40

In [19]:
data[ data[0::,9].astype(np.float) >= fare_ceiling, 9 ] = fare_ceiling - 1.0
fare_bracket_size = 10
number_of_price_brackets = fare_ceiling // fare_bracket_size

In [20]:
number_of_classes = 4

In [21]:
#This is a lie to test a thing

In [22]:
print (number_of_classes)

4


In [23]:
number_of_classes = len(np.unique(data[0::,2])) 

In [24]:
print (number_of_classes)

3


In [25]:
survival_table = np.zeros((2, number_of_classes, number_of_price_brackets))

In [26]:
for i in range(number_of_classes):      
  for j in range(number_of_price_brackets):   
    women_only_stats = data[(data[0::,4] == "female")
                            &(data[0::,2].astype(np.float)== i+1)
                            &(data[0:,9].astype(np.float)>= j*fare_bracket_size)
                            &(data[0:,9].astype(np.float)< (j+1)*fare_bracket_size), 1] 

    men_only_stats = data[(data[0::,4] != "female")
                          &(data[0::,2].astype(np.float)== i+1)
                          &(data[0:,9].astype(np.float)>= j*fare_bracket_size)
                          &(data[0:,9].astype(np.float)< (j+1)*fare_bracket_size), 1] 

In [27]:
  survival_table[0,i,j] = np.mean(women_only_stats.astype(np.float)) 
  survival_table[1,i,j] = np.mean(men_only_stats.astype(np.float))

In [28]:
survival_table[ survival_table != survival_table ] = 0.

In [29]:
print (survival_table)

[[[ 0.     0.     0.     0.   ]
  [ 0.     0.     0.     0.   ]
  [ 0.     0.     0.     0.125]]

 [[ 0.     0.     0.     0.   ]
  [ 0.     0.     0.     0.   ]
  [ 0.     0.     0.     0.24 ]]]


In [30]:
survival_table[ survival_table < 0.5 ] = 0
survival_table[ survival_table >= 0.5 ] = 1 

In [31]:
print (survival_table)

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [32]:
test_file = open('c:/test.csv', 'rt')
test_file_object = csv.reader(test_file)
next(test_file_object)
predictions_file = open('c:/test/genderclassmodel.csv', 'w')
p = csv.writer(predictions_file)
p.writerow(["PassengerId", "Survived"])

22

In [33]:
for row in test_file_object:          
  for j in range(number_of_price_brackets):
    try: 
      row[8] = float(row[8])
    except:     
      bin_fare = 3 - float(row[1])      
      break                          
    if row[8] > fare_ceiling:
                                             
      bin_fare = number_of_price_brackets-1   
      break                                   
    if row[8] >= j * fare_bracket_size\
       and row[8] < \
       (j+1) * fare_bracket_size:           
                                             
      bin_fare = j                          
      break                                   
    if row[3] == 'female':                             
        p.writerow([row[0], "%d" % \
                   int(survival_table[0, float(row[1])-1, bin_fare])])
    else:                                          
        p.writerow([row[0], "%d" % \
                   int(survival_table[1, float(row[1])-1, bin_fare])])
     

test_file.close() 
predictions_file.close()

In [34]:
print (survival_table)

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
